name = "backend"
compatibility_date = "2024-08-22"
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWZiYzAwZjItZDM5NC00NmY1LWJhNDQtYTNlMjI2MjdhZWZjIiwidGVuYW50X2lkIjoiZmQwYmY3ZGE3NGZhZTQ2ZjBiZTc5YTQ5NDk2MDEzNjk1M2RhZGQ1ODI4ZjY0NzYwZjg0MDc5YjFmYmZiZmY4NCIsImludGVybmFsX3NlY3JldCI6ImQ1NTU4YWEwLWYxNDEtNDVkMi05YzU1LWNhMjYzZjllZjBkZSJ9.WZGTFEluZH7l_tAI-uy7LpcsZYAj7mdu4lSJ7ssSsJw"
JWT_SECRET="AjayPratapSinghThakur"

# MY_VAR = "my-variable"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"